from smellycode.smell_compilation import SmellyClass

sc = SmellyClass()
sc.return_String_value(1)
sc.return_String_value(2)
sc.return_String_value(3)
sc.return_String_value(4)
sc.return_String_value(5)
sc.return_String_value(6)
sc.return_String_value(7)
sc.return_String_value(8)
sc.return_String_value(8)
sc.return_String_value(8)
sc.return_String_value(8)
sc.return_String_value(8)
sc.return_String_value(8)
sc.return_String_value(8)
sc.return_String_value(8)
sc.return_String_value(8)
